### ISSUE TITLE
Validate Functional Requirements (Checklist)

### ISSUE THREAD

**Issue by rjmah1** [ECE493-W22-G04/rl-chess#54]
- [X] FR1 - User.Registration - The system shall provide the option of registering a new user by redirecting to the registration form on request.
- [X] FR2 - Secure.Passwords - The system shall encrypt all passwords by hashing and salting the passwords.
- [x] FR3 - Email.Validation - The system shall verify that the inputted email is in a valid email format.
- [X] FR4 - User.Login - The system shall provide the option to login to the system by matching the inputted username and password with the ones stored in the system, returning a token identifying a successful login.
- [X] FR5 - Computer.Setup - The system shall allow the user to set up a game against an AI opponent.
- [X] FR6 - Computer.Move - The system shall make valid moves when it is the AI's turn.
- [X] FR7 - Computer.Model - The system shall utilize a RL based model for the chess AI.
- [x] FR8 - Computer.Learn - The system shall take the game results and use it to update the AI model - Belief Revision.
- [X] FR9 - Computer.Self.Learn - The system shall play against itself (Adversarial Network) in order to get a baseline model.\
- [X] FR10 - Initialize.Lobby - The system shall initialize a new game lobby with the requesting user when the authenticated user clicks the Create Game Lobby button.
- [X] FR11 - Generate.Link - The system shall generate a shareable link to the game lobby so that other players can enter the lobby.
- [X] FR12 - Redirect.Unauthentic.Users - The system shall prompt unauthenticated users to authenticate themselves when they try to enter a game lobby through a shareable URL.
- [X] FR13 - Allow.Authentic.Users - The system shall redirect authenticated users directly to the game lobby when authenticated users try to enter a game lobby through a shareable URL.
- [x] FR14 - Broadcast.New.Players - The system shall broadcast new players entering the lobby to other players already in the lobby.
- [x] FR15 - Display.Players - The system shall display all the players in the lobby to the new player.
- [X] FR16 - Start.Game - The system automatically starts the game when there are two players in the lobby.
- [X] FR17 - Display.Board - The system shall display the same chess board to all players in the lobby
- [X] FR18 - Alternate.Turns - The system shall alternatingly prompt the two active players in the lobby to take their turn.
- [X] FR19 - Detect.Stalemate - The system shall be able to detect stalemates where no players can make a move.
- [X] FR20 - Valid.Move - The system shall prohibit invalid moves and re-prompt the same player to make a valid move.
- [x] FR21 - Board.History - The system shall record and display the list of moves played by each player to reach the current board state.
- [X] FR22 - Detect.Checkmate - The system shall detect when a player is in checkmate and declare the winner.
- [X] FR23 - Detect.Repetition - The system shall detect when a repetition of moves (three times) and declares the game a draw.
- [X] FR24 - Record.Game - The system shall store the winner of the game in the database.
- [X] FR25 - Offer.Draw - The system allows either player to offer a draw on their turn.
- [X] FR26 - Accept.Draw - The system allows an opposing player to accept or reject an offer for a draw.
- [x] FR27 - Store.Draw - The system allows the result of a game to be stored as a draw.
- [X] FR28 - Concede - The system shall allow either player to concede at any time making the opposing player win.
- [x] FR29 - Leave.Game - The system shall concede on behalf of the player if the browser loses connection or the player exits the browser.
- [x] FR30 - Display.Leaderboard - The system displays the leaderboard of players with the highest win rate with a threshold of 10 games played against the computer.
