### ISSUE TITLE
Set-up authentication

### ISSUE THREAD

**Issue by armiantos** [ECE493-W22-G04/rl-chess#7]
* [x] Create login + sign up forms #2
* [x] Set-up postgres server on heroku @armiantos 
* [x] Define player model @jjpatric 
* [x] Tie sign up form with a player entry #10
* [x] Validate player credentials on login from data in database #10
